baseurl: https://nyogjtrc.github.io/
title: "Nyo's Study Book"
languageCode: zh-tw
copyright: "Copyright (c) 2017-2018 nyogjtrc."
theme: hugo-dusk
canonifyurls: true
paginate: 6

googleAnalytics: UA-43264564-2
hasCJKLanguage: true
publishDir: ../nyogjtrc.github.io
permalinks:
      posts: /posts/:year/:month/:filename/

SectionPagesMenu: main

menu:
    main:
        - name: Posts
          weight: -120
          identifier: posts
          url: /posts/
        - name: Tags
          weight: -110
          identifier: tags
          url: /tags/
        - name: About
          weight: -100
          identifier: about
          url: /about/

author:
    name: nyo

params:
    meta:
        keywords: nyo, nyogjtrc, blog, study
        description: 我是 nyo，這是我的軟體開發筆記部落格
    github: nyogjtrc

