baseurl: https://nyogjtrc.github.io/
title: "Nyo's Study Book"
languageCode: zh-tw
# theme: hugo-dusk
# theme: hermit
theme: hugo-coder
canonifyurls: true
paginate: 20

taxonomies:
  tag: tags

googleAnalytics: UA-43264564-2
hasCJKLanguage: true
publishDir: ../nyogjtrc.github.io
permalinks:
  posts: /posts/:year/:month/:filename/

SectionPagesMenu: main

pygmentsStyle: dracula
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true

menu:
  main:
    - name: Posts
      weight: -120
      identifier: posts
      url: /posts/
    - name: Tags
      weight: -110
      identifier: tags
      url: /tags/
    - name: Productivity
      weight: -105
      identifier: productivity
      url: /productivity/
    - name: About
      weight: -100
      identifier: about
      url: /about/

params:
  author: nyo
  description: nyo's study note. researching programming, devops, vim ...etc
  keywords: nyo,nyogjtrc,blog,developer,personal,note
  info: 後端工程師の研究筆記
  avatarurl: https://avatars0.githubusercontent.com/u/515965
  footercontent: nyo, Vim User, Gopher, Keep Learn

  dateform: "Jan 2, 2006"
  dateformShort: "Jan 2"
  dateformNum: "2006-01-02"
  dateformNumTime: "2006-01-02 15:04 -0700"
  #relatedPosts: true

  since: 2015

  colorscheme: dark
  hidecolorschemetoggle: true

  maxSeeAlsoItems: 5

  customcss:
    - "css/custom.css"

  social:
    - name: Github
      icon: "fa fa-github"
      url: https://github.com/nyogjtrc
    - name: Twitter
      icon: "fa fa-twitter"
      url: https://twitter.com/nyogjtrc
    - name: rss
      icon: "fa fa-rss-square"
      url: /index.xml
      type: "application/rss+xml"

