name = "hugo-dusk"
license = "MIT"
licenselink = "https://github.com/gyorb/hugo-dusk/blob/master/LICENSE.md"
description = "A minimalistic dark responsive theme."
homepage = "https://github.com/gyorb/hugo-dusk"
tags = ["blog", "minimal", "clean", "dark"]
features = ["blog"]
min_version = 0.17

[author]
  name = "Gyorgy Orban"
  homepage = "https://github.com/gyorb"
